FROM node:22-slim
RUN apt-get update && apt-get install -y default-jdk
WORKDIR /usr/src/app
# Copy package files (Context will be pointed from outside this folder)
COPY package*.json ./
RUN npm install --production
COPY . .
EXPOSE 5000
CMD ["node", "server.js"]